name: .NET Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "8.0.201"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        working-directory: ./Charity-Finder
        run: |
          dotnet build Charity-Finder.csproj --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-restore --verbosity normal
