name: .NET Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "8.0.201"
      - name: Debug
        working-directory: ./Charity-Finder
        run: |

          pwd
          ls -la

      - run: dotnet test
